### PR TITLE
Ignore Homebrew Git shim

### LINKED ISSUE #676: when brew upgrade: "fatal: Failed to unset Git configuration entry 'credential.https://dev.azure.com.useHttpPath' [1]"
Full output:

```
=> Upgrading 1 outdated package:
microsoft/git/git-credential-manager-core 2.0.632.34631 -> 2.0.696
==> Upgrading git-credential-manager-core
==> Downloading https://github.com/GitCredentialManager/git-credential-manager/releases/do
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset
######################################################################## 100.0%
==> Running uninstall script /usr/local/share/gcm-core/uninstall.sh
Password:
Unconfiguring credential helper...
Unconfiguring component 'Git Credential Manager'...
Unconfiguring component 'Azure Repos provider'...
fatal: Failed to unset Git configuration entry 'credential.https://dev.azure.com.useHttpPath' [1]
git: This shim is internal and must be run via brew.
```

Seemed to upgrade successfully, but just wanted to share this FYI.

### PR DESCRIPTION
**Pull request by ldennington**
Users running `brew uninstall` or `brew upgrade` currently see the following message (indicating that the operation wasn't fully successful):

```
Unconfiguring component 'Azure Repos provider'...
fatal: Failed to unset Git configuration entry 'credential.https://dev.azure.com.useHttpPath' [1]
git: This shim is internal and must be run via brew.
```

This is because GCM is finding the Homebrew Git shim on the PATH and calling it instead of the user's Git installation. Specifying that we should ignore the Homebrew shim when attempting to locate the Git executable on the PATH resolves the issue.

Fixes #676.

### CODE REVIEW

File: src/shared/Core/EnvironmentBase.cs [hunk 1]
```diff
@@ -104,7 +104,12 @@ public virtual Process CreateProcess(string path, string args, bool useShellExec
             return new Process { StartInfo = psi };
         }
 
-        public bool TryLocateExecutable(string program, out string path)
+        public virtual bool TryLocateExecutable(string program, out string path)
+        {
+            return TryLocateExecutable(program, new List<string>(), out path);
+        }
+
+        public bool TryLocateExecutable(string program, List<string> pathsToIgnore, out string path)
```
Comment (mjcheetham) [inline src/shared/Core/EnvironmentBase.cs:112]: Make this method `protected virtual` and accept an `ICollection<string>` instead

```suggestion
        protected virtual bool TryLocateExecutable(string program, ICollection<string> pathsToIgnore, out string path)
```

File: src/shared/Core/EnvironmentBase.cs [hunk 2]
```diff
@@ -104,7 +104,12 @@ public virtual Process CreateProcess(string path, string args, bool useShellExec
             return new Process { StartInfo = psi };
         }
 
-        public bool TryLocateExecutable(string program, out string path)
+        public virtual bool TryLocateExecutable(string program, out string path)
+        {
+            return TryLocateExecutable(program, new List<string>(), out path);
```
Comment (mjcheetham) [inline src/shared/Core/EnvironmentBase.cs:109]: Pass `null` here instead of creating a new heap object

```suggestion
            return TryLocateExecutable(program, null, out path);
```

File: src/shared/Core/EnvironmentBase.cs [hunk 3]
```diff
@@ -124,7 +129,8 @@ public bool TryLocateExecutable(string program, out string path)
                 foreach (var basePath in paths)
                 {
                     string candidatePath = Path.Combine(basePath, program);
-                    if (FileSystem.FileExists(candidatePath))
+                    if (FileSystem.FileExists(candidatePath) &&
+                        !pathsToIgnore.Contains(candidatePath, StringComparer.OrdinalIgnoreCase))
```
Comment (mjcheetham) [inline src/shared/Core/EnvironmentBase.cs:133]: Update to also permit possible `null` arg

```suggestion
                    if (FileSystem.FileExists(candidatePath) && (pathsToIgnore is null ||
                        !pathsToIgnore.Contains(candidatePath, StringComparer.OrdinalIgnoreCase)))
```

File: src/shared/Core/Interop/MacOS/MacOSEnvironment.cs [hunk 4]
```diff
@@ -0,0 +1,34 @@
...
+        {
+            string homebrewPrefix = Environment.GetEnvironmentVariable("HOMEBREW_PREFIX");
+            List<string> pathsToIgnore = new List<string>();
+
+            if (homebrewPrefix != null)
+            {
+                pathsToIgnore.Add($"{homebrewPrefix}/Homebrew/Library/Homebrew/shims/shared/git");
+            }
+
+            return TryLocateExecutable(program, pathsToIgnore, out path);
```
Comment (mjcheetham) [inline src/shared/Core/Interop/MacOS/MacOSEnvironment.cs:31]: Could we possibly cache this ignore list to avoid needing to build it on each invocation? Also we should probably use both the `Variables` member to search for variables and `Path.Combine` to combine the paths.

Unit tests initialise the envars field directly but `Environment.GetEnvironmentVariable()` will look at the _real_ environment.

```suggestion
            if (_pathsToIgnore is null)
            {
                _pathsToIgnore = new List<string>();

                if (Variables.TryGetValue("HOMEBREW_PREFIX", out string homebrewPrefix))
                {
                    string homebrewGit = Path.Combine(homebrewPrefix, "Homebrew/Library/Homebrew/shims/shared/git");
                    _pathsToIgnore.Add(homebrewGit);
                }
            }

            return TryLocateExecutable(program, _pathsToIgnore, out path);
```


..where `_pathsToIgnore` is a private `ICollection<string>` field.

File: src/shared/Core/Interop/MacOS/MacOSEnvironment.cs [hunk 5]
```diff
@@ -0,0 +1,34 @@
...
+    {
+        public MacOSEnvironment(IFileSystem fileSystem)
+            : this(fileSystem, GetCurrentVariables()) { }
+
+        internal MacOSEnvironment(IFileSystem fileSystem, IReadOnlyDictionary<string, string> variables)
+            : base(fileSystem)
+        {
+            EnsureArgument.NotNull(variables, nameof(variables));
+            Variables = variables;
+        }
```
Comment (mjcheetham) [inline src/shared/Core/Interop/MacOS/MacOSEnvironment.cs:19]: We don't need to replicate the constructor of `PosixEnvironment` here – just call through to the corresponding `base` constructor.

```suggestion
        public MacOSEnvironment(IFileSystem fileSystem)
            : base(fileSystem) { }

        internal MacOSEnvironment(IFileSystem fileSystem, IReadOnlyDictionary<string, string> variables)
            : base(fileSystem, variables) { }
```

File: src/shared/Core/Interop/Posix/PosixEnvironment.cs [hunk 6]
```diff
@@ -34,7 +34,7 @@ protected override string[] SplitPathVariable(string value)
 
         #endregion
 
-        private static IReadOnlyDictionary<string, string> GetCurrentVariables()
+        protected static IReadOnlyDictionary<string, string> GetCurrentVariables()
```
Comment (mjcheetham) [inline src/shared/Core/Interop/Posix/PosixEnvironment.cs:37]: We don't need to make this `protected` if we don't need now to call `GetCurrentVariables()` in derived types 😉

File: src/shared/Core.Tests/EnvironmentTests.cs [hunk 7]
```diff
@@ -123,5 +124,31 @@ public void PosixEnvironment_TryLocateExecutable_ExistsMultiple_ReturnTrueAndFir
...
+
+            var fs = new TestFileSystem
+            {
+                Files = new Dictionary<string, byte[]>
+                {
+                    [pathsToIgnore.FirstOrDefault()] = Array.Empty<byte>(),
+                    [expectedPath] = Array.Empty<byte>(),
+                }
+            };
+            var envars = new Dictionary<string, string> {["PATH"] = PosixPathVar};
```
Comment (mjcheetham) [inline src/shared/Core.Tests/EnvironmentTests.cs:145]: Here `PosixPathVar` is `/home/john.doe/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` which doesn't contain the `/home/john.doe/bin/ignore/` directory anyway, so this test will always return `true` since the existing code will not see the `ignore/` dir as existing.

Instead create two empty files at `/home/john.doe/bin/foo` and `/usr/local/bin/foo`, and then set `pathsToIgnore` as `/home/john.doe/bin/foo`.

We already have a test that verifies we should normally select the `john.doe` version ahead of the `usr/local` one, so this test will only pass if the ignored paths feature is correct.

File: src/osx/Installer.Mac/uninstall.sh [hunk 8]
```diff
@@ -12,7 +12,7 @@ fi
 
 # Unconfigure (as the current user)
 echo "Unconfiguring credential helper..."
-sudo -u `/usr/bin/logname` "$GCMBIN" unconfigure
+sudo -u `/usr/bin/logname` HOMEBREW_PREFIX=$HOMEBREW_PREFIX "$GCMBIN" unconfigure
```
Comment (mjcheetham) [inline src/osx/Installer.Mac/uninstall.sh:15]: Aha! The reason `HOMEBREW_PREFIX` wasn't coming through to the GCM process was because we're going via `sudo`. Perhaps we should instead use the following option to preserve _all_ environment variables?

```man
-E, --preserve-env
                   Indicates to the security policy that the user wishes to preserve their existing
                   environment variables.  The security policy may return an error if the user does not have
                   permission to preserve the environment.

```

**Review by mjcheetham — CHANGES_REQUESTED** [review]
A few comments on using `sudo -E` instead and caching the ignore list.

File: src/shared/Core/Interop/MacOS/MacOSEnvironment.cs [hunk 9]
```diff
@@ -0,0 +1,34 @@
...
+
+        public override bool TryLocateExecutable(string program, out string path)
+        {
+            string homebrewPrefix = Environment.GetEnvironmentVariable("HOMEBREW_PREFIX");
+            List<string> pathsToIgnore = new List<string>();
+
+            if (homebrewPrefix != null)
+            {
+                pathsToIgnore.Add($"{homebrewPrefix}/Homebrew/Library/Homebrew/shims/shared/git");
+            }
```
Comment (MikeMcQuaid) [inline src/shared/Core/Interop/MacOS/MacOSEnvironment.cs:29]: Could probably just consider ignoring _any_ path which ends in `Homebrew/Library/Homebrew/shims/shared/git`. That'll save you needing to have `HOMEBREW_PREFIX` be present or passed.

File: src/shared/Core/EnvironmentBase.cs (hunk 1 above)
Comment (ldennington) [reply src/shared/Core/EnvironmentBase.cs]: The UT started complaining with `protected` so I went with `internal` instead.

File: src/shared/Core.Tests/EnvironmentTests.cs (hunk 7 above)
Comment (ldennington) [reply src/shared/Core.Tests/EnvironmentTests.cs:145]: I _think_ I'm picking up what you're putting down. I was at least able to re-configure the test so that it was failing and returning the `/home/john.doe/bin/foo` before I passed `pathsToIgnore`. It then started passing after I passed `pathsToIgnore`. Let me know if further changes are needed, though.

File: src/shared/Core/Interop/MacOS/MacOSEnvironment.cs (hunk 9 above)
Comment (ldennington) [reply src/shared/Core/Interop/MacOS/MacOSEnvironment.cs]: I'm going to roll with the `-E` change Matthew suggested above. Can't hurt to have access to all the `HOMEBREW` variables in future.

File: src/shared/Core.Tests/EnvironmentTests.cs (hunk 7 above)
Comment (mjcheetham) [reply src/shared/Core.Tests/EnvironmentTests.cs:145]: Looks good!

**Review by mjcheetham — APPROVED** [review]
:shipit:

File: src/shared/Core/Interop/MacOS/MacOSEnvironment.cs [hunk 10]
```diff
@@ -0,0 +1,38 @@
...
+            EnsureArgument.NotNull(variables, nameof(variables));
+            Variables = variables;
+        }
+
+        public override bool TryLocateExecutable(string program, out string path)
+        {
+            if (_pathsToIgnore is null)
+            {
+                _pathsToIgnore = new List<string>();
+                if (Variables.TryGetValue("HOMEBREW_PREFIX", out string homebrewPrefix))
```
[the remark this answers is not in the document]
Comment (ldennington) [reply src/shared/Core/Interop/MacOS/MacOSEnvironment.cs:29]: Comment added! Thanks so much again for all your help here, Mike!
